name: Run tests
on: [pull_request]
jobs:
  run_tests:
    runs-on: [self-hosted,gpu]
    strategy:
      matrix:
        python-versions: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}
      - name: build_and_run_examples
        run: |
          pip install .
          pip install pytest
